### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/hadoop/fs/FSDataInputStream

### ISSUE THREAD

**Issue by huylv** [SingularitiesCR/spark-docker#1]
Hi,
Thank you for your contribution. When I tried to test my cluster with `run-example SparkPi 10`, it said

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/fs/FSDataInputStream
    at org.apache.spark.deploy.SparkSubmitArguments.handleUnknown(SparkSubmitArguments.scala:451)
    at org.apache.spark.launcher.SparkSubmitOptionParser.parse(SparkSubmitOptionParser.java:178)
    at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:97)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:114)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.fs.FSDataInputStream
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 5 more
```

Looks like Spark couldn't find Hadoop classpath. How can I fix this? Many thanks.

**Comment by huylv** [comment]
I've found that [line 45 in the Dockerfile](https://github.com/SingularitiesCR/spark-docker/blob/master/Dockerfile#L45) has no effect:

```
&& echo "export SPARK_DIST_CLASSPATH=\$(hadoop classpath)" >> /etc/environment \
```

I need to run `source /etc/environment` to make it work.

**Comment by fjhoelsg** [comment]
Hi @huylv,

Indeed that seems to be the source of the error. The export only works for the same shell session as the entrypoint since it is there were we source it. The value for `SPARK_DIST_CLASSPATH` was set in an export since it was determined by the output of `hadoop classpath`, but I think we can change it so it is also present on the environment. I'll make the change in the build script as soon as I can.

Thanks

**Comment by huylv** [comment]
Thanks for taking your time. Btw, [GettyImages](https://github.com/gettyimages/docker-spark/blob/master/Dockerfile#L57) does exactly what you've described:

```
ENV SPARK_DIST_CLASSPATH="$HADOOP_HOME/etc/hadoop/*:$HADOOP_HOME/share/hadoop/common/lib/*:$HADOOP_HOME/share/hadoop/common/*:$HADOOP_HOME/share/hadoop/hdfs/*:$HADOOP_HOME/share/hadoop/hdfs/lib/*:$HADOOP_HOME/share/hadoop/hdfs/*:$HADOOP_HOME/share/hadoop/yarn/lib/*:$HADOOP_HOME/share/hadoop/yarn/*:$HADOOP_HOME/share/hadoop/mapreduce/lib/*:$HADOOP_HOME/share/hadoop/mapreduce/*:$HADOOP_HOME/share/hadoop/tools/lib/*"
```

Cheers,
Huy

**Comment by fjhoelsg** [comment]
We fixed the issue by setting the export in `$SPARK_HOME/conf/sprak-env.sh`. In addition, we deleted the line that removed the Spark examples; now anyone can run commands like:

``` sh
docker run singularities/spark:1.6 run-example SparkPi 10
```

If this does not fix your issue or you encounter any other issue please let us know.

Thanks

**Comment by huylv** [comment]
Looks good so far. I'll report further if something goes wrong. Thank you so much.

**Comment by kapiljain14** [comment]
Thanks

**Comment by appleyuchi** [comment]
could anyone tell me how to solve it in Intellij?
Thanks~!
