### ISSUE TITLE
pyspark and spark-submit not work inside containers 

### ISSUE THREAD

**Issue by adanba** [SingularitiesCR/spark-docker#2]
Hey,

I try to run **pyspark** and **spark-submit**, but there is something wrong with **python**.

So i got this : 

```
root@sparkmaster:/tmp/test_spark# spark-submit count.py
Exception in thread "main" java.io.IOException: Cannot run program "python": error=2, No such file or directory
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
    at org.apache.spark.deploy.PythonRunner$.main(PythonRunner.scala:82)
    at org.apache.spark.deploy.PythonRunner.main(PythonRunner.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
    at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
    at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.io.IOException: error=2, No such file or directory
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
    at java.lang.ProcessImpl.start(ProcessImpl.java:134)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
    ... 11 more
```

When i try to run **python** only i got this error : 

```
root@sparkmaster:/tmp/test_spark# python
bash: python: command not found


root@sparkmaster:/tmp/test_spark# pyspark
env: python: No such file or directory
```

Do you have any idea ?

Thank you

**Comment by fjhoelsg** [comment]
Hi @adanba,

We recently pushed a new version of the image and, among other things, we included Python 2 and Python 3. Please try to run your script with the new image. If this issue is not fixed please reopen it and we will look into it as soon as possible.

Thank you for your feedback, we really appreciate it.

**Comment by adanba** [comment]
Thank you @fjhoelsg its work for me.
Good Job!

I try it with sparklyr package (RStudio), it's work right.

**Comment by leochen0000** [comment]
Hi I am getting a similar error.
![capture1](https://user-images.githubusercontent.com/39246411/42610801-fb089f6e-8547-11e8-9f26-5af4decb909a.JPG)
