### ISSUE TITLE
Different avro library version

### ISSUE THREAD

**Issue by SrikanthTati** [SingularitiesCR/spark-docker#5]
I got below exception when running a spark app using this docker image.

Driver stacktrace:
        at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1454)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1442)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1441)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1441)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:811)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:811)
...
...
Caused by: java.lang.NoSuchMethodError: org.apache.avro.generic.GenericData.createDatumWriter(Lorg/apache/avro/Schema;)Lorg/apache/avro/io/DatumWriter;
        at org.apache.spark.serializer.GenericAvroSerializer$$anonfun$serializeDatum$1.apply(GenericAvroSerializer.scala:123)
        at org.apache.spark.serializer.GenericAvroSerializer$$anonfun$serializeDatum$1.apply(GenericAvroSerializer.scala:123)
...
...

Same app works fine on my local cluster. That cluster was using spark image that contains hadoop(spark-2.0.2-bin-hadoop2.7). On checking, I noticed that org.apache.avro.io.DatumWriter was being pulled from avro 1.7.7.  **_/opt/spark-2.0.2-bin-hadoop2.7/jars/avro-1.7.7.jar!/org/apache/avro/io/DatumWriter.class_**

This docker image was using version 1.7.4. **_/usr/hadoop-2.7.3/share/hadoop/common/lib/avro-1.7.4.jar!/org/apache/avro/io/DatumWriter.class_**

Not sure how these are different given that both are using hadoop 2.7. Is there any difference in the way this docker image is built as compared to spark distribution? From the stack trace it does appear that spark needs avro 1.7.7.

**Comment by jomarinb** [comment]
Hi @SrikanthTati ,

Apache Avro dependency is a known issue among Spark "Hadoop Free" distributions. In effect, Spark requires Apache Avro v1.7.7, which is provided by them in `/jars` of their hadoop-included distributable and also included inside the `spark-assembly.jar`. Similar issues have been reported in [databricks/spark-avro](https://github.com/databricks/spark-avro) and [spotify/spark-bigquery](https://github.com/spotify/spark-bigquery), refer to:

- [Spark-avro Fails To Write DF in EMR 4.0](https://github.com/databricks/spark-avro/issues/91)
- [Failing to save dataframe to bigquery](https://github.com/spotify/spark-bigquery/issues/11)

A workaround is to download Apache Avro v1.7.7 from a mirror and make it available via `SPARK_DIST_CLASSPATH`, e.g.:

```sh
cd /tmp/
wget http://ftp.cuhk.edu.hk/pub/packages/apache.org/avro/avro-1.7.7/java/avro-1.7.7.jar
rm $HADOOP_HOME/share/hadoop/common/lib/avro-1.7.4.jar
rm $HADOOP_HOME/share/hadoop/mapreduce/lib/avro-1.7.4.jar
sudo cp avro-1.7.7.jar $HADOOP_HOME/share/hadoop/common/lib
sudo mv avro-1.7.7.jar $HADOOP_HOME/share/hadoop/mapreduce/lib
```

I'm going to close this issue for now, but please re-open if you consider it necessary.
